#!/bin/bash
source $( dirname -- "${BASH_SOURCE[0]}" )/00-env

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})
# get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
SYSTEM_UPTIME=`uptime -p`

out=""
out+="${creset}Uptime:| $SYSTEM_UPTIME\n"
out+="Load:| ${green}$LOAD1${creset}, ${green}$LOAD5${creset}, ${green}$LOAD15${creset}\n"
out+="Processes:| ${green}$PROCESS_ALL ${dim}($PROCESS_ROOT root, $PROCESS_USER user)${creset}\n"
out+="Memory:| ${green}$USED${white} used, ${green}$AVAIL${white} avail, ${green}$TOTAL${white} total\n"

printf "\n${uline}system stats${creset}\n"
printf "$out" | column -ts $'|' | sed -e 's/^/  /'
